if ROLE in('INPUT', 'REJECTED') then do;
if upcase(NAME) in(
'IMP_PH'
'IMP_SULPHATES'
'TASTERNAME'
'TASTINGDATE'
'ALCOHOL'
'CATEGORY'
'CHLORIDES'
'CITRIC_ACID'
'DENSITY'
'FIXED_ACIDITY'
'FREE_SULFUR_DIOXIDE'
'TOTAL_SULFUR_DIOXIDE'
'VOLATILE_ACIDITY'
) then ROLE='INPUT';
else delete;
end;
