if NAME="Country" then do;
ROLE="REJECTED";
LEVEL="NOMINAL";
ORDER="";
end;
if NAME="Price" then do;
ROLE="REJECTED";
LEVEL="INTERVAL";
ORDER="";
end;
if NAME="ProduceDate" then do;
ROLE="REJECTED";
LEVEL="INTERVAL";
ORDER="";
end;
if NAME="QuantitySold" then do;
ROLE="REJECTED";
LEVEL="INTERVAL";
ORDER="";
end;
if NAME="Sequence_Tasting" then do;
ROLE="REJECTED";
LEVEL="INTERVAL";
ORDER="";
end;
if NAME="TasterName" then do;
ROLE="CROSSID";
LEVEL="NOMINAL";
ORDER="";
end;
if NAME="alcohol" then do;
ROLE="REJECTED";
LEVEL="INTERVAL";
ORDER="";
end;
if NAME="category" then do;
ROLE="CROSSID";
LEVEL="NOMINAL";
ORDER="";
end;
if NAME="chlorides" then do;
ROLE="REJECTED";
LEVEL="INTERVAL";
ORDER="";
end;
if NAME="citric_acid" then do;
ROLE="REJECTED";
LEVEL="INTERVAL";
ORDER="";
end;
if NAME="density" then do;
ROLE="REJECTED";
LEVEL="INTERVAL";
ORDER="";
end;
if NAME="fixed_acidity" then do;
ROLE="REJECTED";
LEVEL="INTERVAL";
ORDER="";
end;
if NAME="free_sulfur_dioxide" then do;
ROLE="REJECTED";
LEVEL="INTERVAL";
ORDER="";
end;
if NAME="index" then do;
ROLE="REJECTED";
LEVEL="INTERVAL";
ORDER="";
end;
if NAME="pH" then do;
ROLE="REJECTED";
LEVEL="INTERVAL";
ORDER="";
end;
if NAME="quality" then do;
ROLE="TARGET";
LEVEL="INTERVAL";
ORDER="";
end;
if NAME="residual_sugar" then do;
ROLE="REJECTED";
LEVEL="INTERVAL";
ORDER="";
end;
if NAME="sulphates" then do;
ROLE="REJECTED";
LEVEL="INTERVAL";
ORDER="";
end;
if NAME="total_sulfur_dioxide" then do;
ROLE="REJECTED";
LEVEL="INTERVAL";
ORDER="";
end;
if NAME="volatile_acidity" then do;
ROLE="REJECTED";
LEVEL="INTERVAL";
ORDER="";
end;
drop DROP;
