fixed_acidity= "fixed acidity"n;
Label fixed_acidity='fixed acidity';
drop "fixed acidity"n;
volatile_acidity= "volatile acidity"n;
Label volatile_acidity='volatile acidity';
drop "volatile acidity"n;
citric_acid= "citric acid"n;
Label citric_acid='citric acid';
drop "citric acid"n;
residual_sugar= "residual sugar"n;
Label residual_sugar='residual sugar';
drop "residual sugar"n;
free_sulfur_dioxide= "free sulfur dioxide"n;
Label free_sulfur_dioxide='free sulfur dioxide';
drop "free sulfur dioxide"n;
total_sulfur_dioxide= "total sulfur dioxide"n;
Label total_sulfur_dioxide='total sulfur dioxide';
drop "total sulfur dioxide"n;
