if NAME="Country" then do;
ROLE="REJECTED";
LEVEL="NOMINAL";
ORDER="";
end;
if NAME="Price" then do;
ROLE="REJECTED";
LEVEL="INTERVAL";
ORDER="";
end;
if NAME="ProduceDate" then do;
ROLE="REJECTED";
LEVEL="INTERVAL";
ORDER="";
end;
if NAME="QuantitySold" then do;
ROLE="REJECTED";
LEVEL="INTERVAL";
ORDER="";
end;
if NAME="TasterName" then do;
ROLE="REJECTED";
LEVEL="NOMINAL";
ORDER="";
end;
if NAME="TastingDate" then do;
ROLE="REJECTED";
LEVEL="INTERVAL";
ORDER="";
end;
if NAME="index" then do;
ROLE="REJECTED";
LEVEL="INTERVAL";
ORDER="";
end;
if NAME="quality" then do;
ROLE="TARGET";
LEVEL="INTERVAL";
ORDER="";
end;
drop DROP;
