*------------------------------------------------------------*;
* TRANSFORM: alcohol , log10(alcohol + 1);
*------------------------------------------------------------*;
label LG10_alcohol = 'Transformed alcohol';
if alcohol eq . then LG10_alcohol = .;
else do;
if alcohol + 1 > 0 then LG10_alcohol = log10(alcohol + 1);
else LG10_alcohol = .;
end;
*------------------------------------------------------------*;
* TRANSFORM: chlorides , log10(chlorides + 1);
*------------------------------------------------------------*;
label LG10_chlorides = 'Transformed chlorides';
if chlorides eq . then LG10_chlorides = .;
else do;
if chlorides + 1 > 0 then LG10_chlorides = log10(chlorides + 1);
else LG10_chlorides = .;
end;
*------------------------------------------------------------*;
* TRANSFORM: citric_acid , log10(citric_acid + 1);
*------------------------------------------------------------*;
label LG10_citric_acid = 'Transformed: citric acid';
if citric_acid eq . then LG10_citric_acid = .;
else do;
if citric_acid + 1 > 0 then LG10_citric_acid = log10(citric_acid + 1);
else LG10_citric_acid = .;
end;
*------------------------------------------------------------*;
* TRANSFORM: density , log10(density + 1);
*------------------------------------------------------------*;
label LG10_density = 'Transformed density';
if density eq . then LG10_density = .;
else do;
if density + 1 > 0 then LG10_density = log10(density + 1);
else LG10_density = .;
end;
*------------------------------------------------------------*;
* TRANSFORM: fixed_acidity , log10(fixed_acidity + 1);
*------------------------------------------------------------*;
label LG10_fixed_acidity = 'Transformed: fixed acidity';
if fixed_acidity eq . then LG10_fixed_acidity = .;
else do;
if fixed_acidity + 1 > 0 then LG10_fixed_acidity = log10(fixed_acidity + 1);
else LG10_fixed_acidity = .;
end;
*------------------------------------------------------------*;
* TRANSFORM: free_sulfur_dioxide , log10(free_sulfur_dioxide + 1);
*------------------------------------------------------------*;
label LG10_free_sulfur_dioxide = 'Transformed: free sulfur dioxide';
if free_sulfur_dioxide eq . then LG10_free_sulfur_dioxide = .;
else do;
if free_sulfur_dioxide + 1 > 0 then LG10_free_sulfur_dioxide = log10(free_sulfur_dioxide + 1);
else LG10_free_sulfur_dioxide = .;
end;
*------------------------------------------------------------*;
* TRANSFORM: total_sulfur_dioxide , log10(total_sulfur_dioxide + 1);
*------------------------------------------------------------*;
label LG10_total_sulfur_dioxide = 'Transformed: total sulfur dioxide';
if total_sulfur_dioxide eq . then LG10_total_sulfur_dioxide = .;
else do;
if total_sulfur_dioxide + 1 > 0 then LG10_total_sulfur_dioxide = log10(total_sulfur_dioxide + 1);
else LG10_total_sulfur_dioxide = .;
end;
*------------------------------------------------------------*;
* TRANSFORM: volatile_acidity , log10(volatile_acidity + 1);
*------------------------------------------------------------*;
label LG10_volatile_acidity = 'Transformed: volatile acidity';
if volatile_acidity eq . then LG10_volatile_acidity = .;
else do;
if volatile_acidity + 1 > 0 then LG10_volatile_acidity = log10(volatile_acidity + 1);
else LG10_volatile_acidity = .;
end;
